cloud:
  aws:
    access-key: ""
    secret-key: ""
    region: ap-southeast-1
    bucket-name: book-app-demo-storage
    bucket-url-secret: bucket-file-url
    sender-grid-secret-name: email-sender-api-key