datasource:
  username: pacifique
  password: pacifique
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/storedb
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect