services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=storedb'
      - 'POSTGRES_PASSWORD=pacifique'
      - 'POSTGRES_USER=pacifique'
    ports:
      - '5432:5432'
    restart: unless-stopped