cloud:
  aws:
    access-key: AKIAT7WPJ6YGONBZNPNI
    secret-key: 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
    region: ap-southeast-1
    bucket-name: user-profiles-bucket
    bucket-url-secret: bucket-file-url
    bucket-url-endpoint: https://user-profiles-bucket.s3.ap-southeast-1.amazonaws.com/
    sender-grid-secret-name: sender-grid-secret-keys