jwt:
  testing-config-auth-token:
    secret-key: 2D4A614E645267556B58703272357538782F413F4428472B4B6250655368566D
    internal-api-key: springbootbackendapplicationsecretinternalkey1234
    token-prefix: Bearer
email-config:
  email-sender : user@gmail.com
  sender-grid: false